<?php

namespace AppBundle\Repository;

/**
 * MediaFolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaFolderRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteAll()
    {
        $em = $this->getEntityManager();
        foreach ($this->findAll() as $m) {
            $em->remove($m);
        }
        $em->flush();
    }

    public function mediaFolderExistsByTriple($mediaFileTriple)
    {
        $em = $this->getEntityManager();

        $mediaDriveName = $mediaFileTriple->mediaDrivePath;
        $mediaFolderName = $mediaFileTriple->mediaFolderPath;

        $dql = <<<DQL
SELECT
    folder.id
    FROM AppBundle:MediaFolder folder
        INNER JOIN AppBundle:MediaDrive drive WITH folder.mediaDrive = drive
    WHERE
        drive.mediaFileBaseFolder=:driveName AND
        folder.path=:folderName
DQL;

        $retId=$em
            ->createQuery($dql)
            ->setMaxResults(1)
            ->setParameter('folderName', $mediaFolderName)
            ->setParameter('driveName', $mediaDriveName)
            ->getResult();


        $retId = @$retId[0]['id'];

        $ret = $retId ? $this->findOneById($retId) : null;
        return $ret;

    }


}
