<?php

namespace AppBundle\Repository;

/**
 * MediaDriveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaDriveRepository extends \Doctrine\ORM\EntityRepository
{


    public function deleteAll()
    {
        $em = $this->getEntityManager();
        foreach ($this->findAll() as $m) {
            $em->remove($m);
        }
        $em->flush();
    }

    public function mediaDriveExistsByTriple($mediaFileTriple)
    {
        $em = $this->getEntityManager();

        $mediaDriveName = $mediaFileTriple->mediaDrivePath;

        $dql = <<<DQL
SELECT
    drive.id
    FROM AppBundle:MediaDrive drive
    WHERE
        drive.mediaFileBaseFolder=:driveName
DQL;

        $retId=$em
            ->createQuery( $dql )
            ->setMaxResults(1)
            ->setParameter('driveName', $mediaDriveName)
            ->getResult();
        $retId = @$retId[0]['id'];

        $ret = $retId ? $this->findOneById($retId) : null;
        return $ret;

    }


}
